### ISSUE TITLE
Can we have HList / HMap / HSet on steroids to define structural data and relationships

### ISSUE THREAD

**Issue by sirinath** [silt-lang/silt#23]
Can we have HList / HMap / HSet such that they can be basis of defining structural and both nominative record types. Nominative typing need not mimic OO conventions faithfully but many of what can be done with OO should be doable using above. Also the ability to defining structural data like XML or JSON based these structures. Also you should be easily move from purely structural data representation to graph based hierarchical data and back again easily.

**Comment by CodaFi** [comment]
All of this is speculation because this question comes at a time when we haven’t even begun work on the Semantic phase.  My thoughts up to this point are inline:

> Can we have HList / HMap / HSet such that they can be basis of defining structural and both nominative record types.

In a nominal dependent system like we’re going for, you can define these structures internally.  However, I’m not sure what you mean by “on steroids” (something like [Vinyl Records](https://hackage.haskell.org/package/vinyl)?)  

We certainly don’t need a notion of first-class structural typing in order to get this working.

> Nominative typing need not mimic OO conventions faithfully but many of what can be done with OO should be doable using above. 

Elaborate. This doesn’t make sense to me.

**Comment by sirinath** [comment]
I am not very familiar with Vinyl and Haskell but in essence it is record kung fu that I had in mind. This can be used to mimic inheritance and other complex structured data.

In nominatively typed hierarchies, there is an additional check of the name. This means the records can be name tagged. Also the name symbols can be part of a hierarchy. If symbol `C` is a subtype of `A` and `B` a record with name tag of `C` is a subtype of record with name tag `A` and `B`. `C` is essentially `A` & 'B'. Also to extract common type you can have the notion of `x` | `y`.

If a record does not have a symbol and a name tag it is treated as structural type.

Also you can have record initializes which can serve the purpose of object instantiation.

**Comment by harlanhaskins** [comment]
I'm still having trouble understanding the language-level implications of this. @codafi Does our type system even allow for the kind of sub typing relationships described above?

Would this necessitate adding the rule that

```
record Foo where
  field a : Int
  field b : Bool
```

be a subtype of

```
record Bar where
  field a : Int
```

? If so, I don't necessarily want that in the language.

**Comment by CodaFi** [comment]
Like I said, we don’t need subtyping for this.  The way Vinyl does it is you declare (or derive) an HList-like structure and a bunch of accessors for fields that are statically known to exist.  Subtyping is witnessed by producing an instance of this data structure

```agda
data _<:_ : (sub : List k) (super : List k) -> Type where
  | SublistNil   : <> <: <>
  | SublistSuper : {r}{sub : List k}{super : List k} -> sub <: super -> sub <: (r :: super)
  | SublistBoth  :  {r}{sub : List k}{super : List k} -> sub <: super -> (r :: sub) <: (r :: super)
```
