### ISSUE TITLE
Unsatisfying diagnostic if user forgot to declare a module

### ISSUE THREAD

**Issue by harlanhaskins** [silt-lang/silt#36]
### Version

`eaace937`

### Environment

macOS, though this is universal.

### Description

Right now, if you open a file without specifying a module, you get this unsatisfying diagnostic:
```haskell
id x = x
```

```
issue.silt:1:1: error: unexpected token 'id' (expected 'module')
```

I'd prefer to see:
- The parser handle recovery, usually by making a dummy module.
- A better diagnostic that tells the user that a module is required at the top of every file.

### Additional Information

You could accomplish this by doing a check in `Parser.parseModule` and providing another, better diagnostic. You'd then need to update the diagnostic test in `DiagnosticTests/Resources/no-module.silt`.

**Comment by harlanhaskins** [comment]
@felix91gr: This would be a great place to get started helping 😅

**Comment by felix91gr** [comment]
Okay! Sounds simple enough :)

I’m gonna set up a reminder for December. Right now I’m collapsing with the final assignments 😅

**Comment by harlanhaskins** [comment]
I hear you on that! I’ll assign you, but no pressure 😄

**Comment by felix91gr** [comment]
Okay 😊

**Comment by SD10** [comment]
@harlanhaskins What do you mean by:

> - The parser handle recovery, usually by making a dummy module.

Is there an existing example of any similar behavior in the project?

**Comment by harlanhaskins** [comment]
I think a full system of parser recovery is out of scope for this bug fix, so I’ll make a separate issue for it. Right now, the parser falls over on the first parse error, which makes for a bad experience with large files.

**Comment by harlanhaskins** [comment]
Ideally, if we fail parsing something, we walk forward to the end of the current scope and then continue trying to parse.
