### ISSUE TITLE
[RFC] Get a barebones scheduler working

### ISSUE THREAD

**Issue by harlanhaskins** [silt-lang/silt#93]
### Description

Graph IR is, fundamentally, a set of interconnected nodes. That doesn't lend itself well to SSA construction, so we instead must 'schedule' operations to establish an ordering of primitive operations and yield us a form amenable to SSA translation.

This is also the time where we infer the necessary destroy/copy operations via the ownership characteristics of Continuation parameters.

## Primitive Operations

In #91, @CodaFi started detailing some primitive operations, each of which needs a representation for scheduling.

| Operation | Operands | Description |
|-----------|-----------|-------------|
| `function_ref` | `(Continuation)` | Retrieves a value representing a reference to a top-level function that can be passed at runtime. |
| `copy_value` | `(Value)` | Calls the provided value's underlying copy constructor, copying the value into a new storage location |
| `destroy_value` | `(Value)` | Calls the provided value's destructor. This can only be done by a continuation that has ownership of its parameters and does not pass them to another continuation. |
| `switch_constr` | `(Value, [(Constructor, Continuation)])` | Determines which constructor was used to instantiate the provided value, and calls that continuation, passing the value and the outer continuation along. |
| data_init_simple | `(Constructor)` | Calls the provided zero-argument constructor and creates a boxed value containing the result of construction. |
| data_init | `(Constructor, [Value])` | Calls the provided constructor and creates a boxed value containing the result of construction. |

(These are probably the wrong descriptions and semantics, but I want them written down.)

**Comment by CodaFi** [comment]
Resolved by #91
